version: "3.8"

x-base:
  &base
  restart: always
  env_file:
    - .env

services:

  # homer:
  #   <<: *base
  #   image: b4bz/homer
  #   container_name: homer
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./homer:/www/assets

  transmission:
    <<: *base
    image: linuxserver/transmission
    container_name: transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./transmission:/config
      - ${STORAGE}/downloads:/downloads
      - ${STORAGE}/blackhole:/watch
      - ${STORAGE}/shows:/data/shows
      - ${STORAGE}/movies:/data/movies

  sonarr:
    <<: *base
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - ./sonarr:/config
      - ${STORAGE}/shows:/data/shows
      - ${STORAGE}/downloads/complete:/downloads

  radarr:
    <<: *base
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - ./radarr:/config
      - ${STORAGE}/movies:/movies
      - ${STORAGE}/downloads/complete:/downloads

  jellyfin:
    <<: *base
    image: linuxserver/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ./jellyfin:/config
      - ${STORAGE}/shows:/data/shows
      - ${STORAGE}/movies:/data/movies

  jackett:
    <<: *base
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - ./jackett:/config
      - ${STORAGE}/blackhole:/downloads
