version: "3"

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    volumes:
      - ./transmission:/config
      - ${STORAGE}/downloads:/downloads
      - ${STORAGE}/blackhole:/watch
    env_file:
      - .env

  emby:
    image: linuxserver/emby
    container_name: emby
    restart: always
    ports:
      - 8096:8096
      - 8920:8920
    expose:
      - 8096
    volumes:
      - ./emby:/config
      - ${STORAGE}/shows:/data/tvshows
      - ${STORAGE}/movies:/data/movies
    env_file:
      - .env

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    ports:
      - 9117:9117
    expose:
      - 9117
    volumes:
      - ./jackett:/config
      - ${STORAGE}/blackhole:/downloads
    env_file:
      - .env

  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    restart: always
    ports:
      - 8989:8989
    expose:
      - 8989
    volumes:
      - ./sonarr:/config
      - ${STORAGE}/shows:/tv
      - ${STORAGE}/downloads/complete:/downloads
    env_file:
      - .env

  radarr:
    image: linuxserver/radarr:preview
    container_name: radarr
    restart: always
    ports:
      - 7878:7878
    expose:
      - 7878
    volumes:
      - ./radarr:/config
      - ${STORAGE}/movies:/movies
      - ${STORAGE}/downloads/complete:/downloads
    env_file:
      - .env
